ll = -L /home/king/work/sqlite3/sqlite3-arm/lib/ -I /home/king/work/sqlite3/sqlite3-arm/include/ -lsqlite3
login.cgi:login.c cgic.h cgic.c
	arm-linux-gcc -Wall login.c cgic.c -o login.cgi $(ll)
	cp login.cgi ../../www/cgi-bin/
