ll = -L /home/king/work/sqlite3/sqlite3-arm/lib/ -I /home/king/work/sqlite3/sqlite3-arm/include/ -lsqlite3
record.cgi:record.c cgic.h cgic.c
	arm-linux-gcc -Wall record.c cgic.c -o record.cgi $(ll)
	cp record.cgi ../../www/cgi-bin/
